"use client";

import type { ColorAnalysisResult } from "@/types/colorAnalysis";

function drawColorRow(ctx: CanvasRenderingContext2D, colors: { hex: string; name: string }[], x: number, y: number, swatchSize: number, gap: number): number {
  colors.forEach((c, i) => {
    const cx = x + i * (swatchSize + gap);
    ctx.fillStyle = c.hex;
    ctx.beginPath();
    ctx.roundRect(cx, y, swatchSize, swatchSize, 6);
    ctx.fill();
    ctx.fillStyle = "#666";
    ctx.font = "9px Inter, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText(c.name, cx + swatchSize / 2, y + swatchSize + 12, swatchSize + gap - 4);
  });
  return y + swatchSize + 24;
}

export function generatePdfCanvas(result: ColorAnalysisResult): HTMLCanvasElement {
  const W = 1080;
  const H = 1920;
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d")!;

  // Background
  ctx.fillStyle = "#FAF5EB";
  ctx.fillRect(0, 0, W, H);

  // Header band
  ctx.fillStyle = "#2C2C2C";
  ctx.fillRect(0, 0, W, 200);
  ctx.fillStyle = "#FAF5EB";
  ctx.font = "bold 14px 'JetBrains Mono', monospace";
  ctx.letterSpacing = "4px";
  ctx.textAlign = "center";
  ctx.fillText("PERSONAL COLOR ANALYSIS", W / 2, 50);
  ctx.letterSpacing = "0px";
  ctx.font = "bold 48px 'DM Serif Display', serif";
  ctx.fillText(result.season.primary, W / 2, 120);
  ctx.font = "14px 'JetBrains Mono', monospace";
  ctx.fillStyle = "#B8C5A2";
  ctx.fillText(`${result.season.confidence}% CONFIDENCE  ·  ${result.undertone.undertone.toUpperCase()} UNDERTONE  ·  ${result.contrast.contrast.toUpperCase()} CONTRAST`, W / 2, 165);

  let curY = 240;

  // Face attributes
  ctx.textAlign = "left";
  ctx.fillStyle = "#2C2C2C";
  ctx.font = "bold 22px 'DM Serif Display', serif";
  ctx.fillText("Your Natural Coloring", 60, curY);
  curY += 30;
  ctx.font = "14px Inter, sans-serif";
  ctx.fillStyle = "#666";
  const attrs = [
    `Skin: ${result.face_attributes.skin_tone}`,
    `Eyes: ${result.face_attributes.eye_color}`,
    `Hair: ${result.face_attributes.hair_color}`,
    `Lips: ${result.face_attributes.lip_color}`,
  ];
  attrs.forEach((a) => {
    ctx.fillText(a, 60, curY);
    curY += 22;
  });

  curY += 20;

  // Best colors
  ctx.fillStyle = "#2C2C2C";
  ctx.font = "bold 22px 'DM Serif Display', serif";
  ctx.fillText("Your Best Colors", 60, curY);
  curY += 20;
  const colorRows = [];
  for (let i = 0; i < result.best_colors.length; i += 8) {
    colorRows.push(result.best_colors.slice(i, i + 8));
  }
  colorRows.forEach((row) => {
    curY = drawColorRow(ctx, row, 60, curY, 100, 16);
    curY += 8;
  });

  curY += 10;

  // Avoid colors
  ctx.fillStyle = "#2C2C2C";
  ctx.font = "bold 22px 'DM Serif Display', serif";
  ctx.fillText("Colors to Avoid", 60, curY);
  curY += 20;
  curY = drawColorRow(ctx, result.avoid_colors, 60, curY, 80, 14);

  curY += 20;

  // Narrative
  ctx.fillStyle = "#2C2C2C";
  ctx.font = "bold 22px 'DM Serif Display', serif";
  ctx.fillText("Toastie Says", 60, curY);
  curY += 24;
  ctx.font = "14px Inter, sans-serif";
  ctx.fillStyle = "#555";
  const words = result.narrative.split(" ");
  let line = "";
  const maxW = W - 120;
  words.forEach((word) => {
    const test = line + word + " ";
    if (ctx.measureText(test).width > maxW && line) {
      ctx.fillText(line.trim(), 60, curY);
      curY += 20;
      line = word + " ";
    } else {
      line = test;
    }
  });
  if (line.trim()) {
    ctx.fillText(line.trim(), 60, curY);
    curY += 20;
  }

  // Footer
  ctx.fillStyle = "#CCC";
  ctx.font = "11px 'JetBrains Mono', monospace";
  ctx.textAlign = "center";
  ctx.fillText("Generated by Toastie — Burnt Toast AI Stylist", W / 2, H - 40);
  ctx.fillText(new Date(result.created_at).toLocaleDateString(), W / 2, H - 22);

  return canvas;
}

export function downloadPdf(result: ColorAnalysisResult) {
  const canvas = generatePdfCanvas(result);
  const link = document.createElement("a");
  link.download = `color-analysis-${result.season.primary.toLowerCase().replace(/\s+/g, "-")}.png`;
  link.href = canvas.toDataURL("image/png");
  link.click();
}
